export default {
  products: [
    {
      _id: "1",
      name: "Slim shirt",
      category: "shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.0,
      numRew: 10,
      countInStock: 0,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry",
    },
    {
      _id: "2",
      name: "Big shirt",
      category: "shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.0,
      numRew: 10,
      countInStock: 2,
      description: "Lorem Ipsum is simply dummy text ",
    },

    {
      _id: "3",
      name: "Slim shirt",
      category: "shirt",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Addidas",
      rating: 1.0,
      numRew: 100,
      countInStock: 10,
      description: "Lorem Ipsum",
    },
    {
      _id: "4",
      name: "Slim shirt",
      category: "shirt",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Addidas",
      rating: 1.0,
      numRew: 100,
      countInStock: 8,
      description: "Test beskrivelse",
    },
    {
      _id: "5",
      name: "Extra big shirt",
      category: "shirt",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Dressman",
      rating: 3.0,
      numRew: 900,
      countInStock: 10,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    },
    {
      _id: "6",
      name: "Extra extra big big shirt",
      category: "shirt",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Dressman",
      rating: 5.0,
      numRew: 900,
      countInStock: 9,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry",
    },
  ],
};
