export const PRODUCT_LIST_REQUST = "PRODUCT_LIST_REQUST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
//Details
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS;";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const PRODUCT_SAVE_REQUEST = "PRODUCT_SAVE_REQUEST";
export const PRODUCT_SAVE_SUCCESS = "PRODUCT_SAVE_SUCCESS;";
export const PRODUCT_SAVE_FAIL = "PRODUCT_SAVE_FAIL";
