// <auto-generated />
namespace WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adding_Key_to_orderToProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_Key_to_orderToProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191813325_adding_Key_to_orderToProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
