// <auto-generated />
namespace WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deleted_orders_in_OrderToProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleted_orders_in_OrderToProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191802091_deleted_orders_in_OrderToProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
